<a href="https://colab.research.google.com/github/vinisouz4/BasicDeepLearning/blob/main/DeepLearningEstudo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constantes

In [54]:
import tensorflow as tf

In [55]:
# Criando as constantes
valor1 = tf.constant(2)
valor2 = tf.constant(3)

In [56]:
# printando os valores das constantes
print(valor1)
print(valor2)

# Shape => é o tamanho ou o formato da constante, e está vazio porque é numero escalar

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [57]:
# Somando os valores das constantes
# Aqui ele gera um grafo
soma = valor1 + valor2

In [58]:
soma

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [59]:
texto1 = tf.constant('Texto 1 ')
texto2 = tf.constant('Texto 2')

In [60]:
texto1

<tf.Tensor: shape=(), dtype=string, numpy=b'Texto 1 '>

In [61]:
# Concatenar duas strings com o tensorflow
# b -> bites literal
concat = texto1 + texto2
concat

<tf.Tensor: shape=(), dtype=string, numpy=b'Texto 1 Texto 2'>

# Variaveis

In [62]:

# Sempre colocar o parametro *name* o nome da variavel para facilitar em projetos maiores
valor1 = tf.constant(15, name='valor1')
print(valor1)

tf.Tensor(15, shape=(), dtype=int32)


In [63]:
# Definindo variaveis no TensorFlow, no qual ele define como será o grafo, já com a criação de sessão
soma = tf.Variable(valor1 + 5, name="valor1")
soma

<tf.Variable 'valor1:0' shape=() dtype=int32, numpy=20>

In [64]:
# No retorno é mostrado que tem uma lista (vetor), no parametro shape me mostra que temos 3 itens dentro do meu vetor
vetor = tf.constant([5, 10, 15], name='vetor')
vetor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 10, 15], dtype=int32)>

In [65]:
# Criar uma soma no qual pegue todos os meus valores do vetor e some por 5
soma = tf.Variable(vetor + 5, name='soma')
soma

<tf.Variable 'soma:0' shape=(3,) dtype=int32, numpy=array([10, 15, 20], dtype=int32)>

In [66]:
valor = tf.Variable(0, name='valor')

# Looping no qual ele pega um range e incrementa na minha variabel
for i in range(5):
  valor = valor + 1
  print(valor)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


# Adição de Vetores e Matrizes

In [67]:
a = tf.constant([9,8,7], name='a')
b = tf.constant([1,2,3], name='b')

In [68]:
# Vou fazer a soma dos itens da minha lista a com a minha lista b
soma = a + b
soma

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [69]:
# No parametro shape ele me mostra que temos duas colunas (duas listas) com 3 itens dentro delas
a1 = tf.constant([[1,2,3], [4,5,6]], name = 'a1')
a1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [70]:
a1.shape

TensorShape([2, 3])

In [71]:
b1 = tf.constant([[1,2,3], [4,5,6]], name="b1")
b1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [72]:
# O parametro .add é uma soma usando as prioridades do TensorFlow
soma = tf.add(a1, b1)
soma

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [73]:
soma.numpy()

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [78]:
a2 = tf.constant([[1,2,3], [4,5,6]], name='a2')
b2 = tf.constant([[1], [2]], name='b2')
soma = tf.add(a2, b2)
soma

# with tf.compat.v1.Session() as sess:
#   print(sess.run(soma))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [6, 7, 8]], dtype=int32)>

# Multiplicações de Matrizes

In [79]:
a = tf.constant([[1,2], [3,4]], name='a')
b = tf.constant([[-1,3], [4,2]], name='b')

In [82]:
# Realizando a multiplicação entre matrizes entre A e B
multiplicacao = tf.matmul(a,b)
multiplicacao

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  7],
       [13, 17]], dtype=int32)>

In [83]:
multiplicacao2 = tf.matmul(b,a)
multiplicacao2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 10],
       [10, 16]], dtype=int32)>

In [84]:
a1 = tf.constant([[2,3], [0,1], [-1,4]])
b1 = tf.constant([[1,2,3], [-2,0,4]])
multiplicacao3 = tf.matmul(a1,b1)
multiplicacao3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-4,  4, 18],
       [-2,  0,  4],
       [-9, -2, 13]], dtype=int32)>